import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config({ path: "./.env" });
import Course from "../models/Course.js";
import Certification from "../models/Certification.js";

const courses = [
  { title: "Data Structures & Algorithms in C++", provider: "Scaler", url: "https://www.scaler.com/dsa-course/", description: "Master DSA fundamentals with 300+ problems and live sessions by industry experts.", skills: ["c++","data structures","algorithms","problem solving","competitive programming"], category: "Computer Science", duration: "6 months", difficulty: "Intermediate", rating: 4.6, price: { amount: 19999, currency: "INR", isFree: false }, certificationProvided: true },
  { title: "Full Stack Development with Web Dev", provider: "Scaler", url: "https://www.scaler.com/full-stack-course/", description: "End-to-end web development with React, Node.js, databases, and deployment.", skills: ["html","css","javascript","react","node.js","mongodb","express","typescript"], category: "Web Development", duration: "8 months", difficulty: "Intermediate", rating: 4.5, price: { amount: 29999, currency: "INR", isFree: false }, certificationProvided: true },
  { title: "Machine Learning with Python", provider: "Scaler", url: "https://www.scaler.com/ml-course/", description: "ML fundamentals, deep learning, NLP, and computer vision with real projects.", skills: ["python","machine learning","tensorflow","pandas","numpy","deep learning"], category: "AI/ML", duration: "7 months", difficulty: "Advanced", rating: 4.4, price: { amount: 24999, currency: "INR", isFree: false }, certificationProvided: true },
  { title: "Full Stack Web Development", provider: "PW Skills", url: "https://www.pwskills.com/course/full-stack-web-development", description: "Complete web dev bootcamp covering HTML, CSS, JS, React, Node.js, MongoDB.", skills: ["html","css","javascript","react","node.js","mongodb","express"], category: "Web Development", duration: "6 months", difficulty: "Beginner", rating: 4.3, price: { amount: 4999, currency: "INR", isFree: false }, certificationProvided: true },
  { title: "Data Science with Python", provider: "PW Skills", url: "https://www.pwskills.com/course/data-science", description: "Learn data analysis, visualization, ML, and statistics with real-world projects.", skills: ["python","pandas","numpy","data analysis","machine learning","sql"], category: "Data Science", duration: "5 months", difficulty: "Beginner", rating: 4.2, price: { amount: 3999, currency: "INR", isFree: false }, certificationProvided: true },
  { title: "Cloud Computing with AWS", provider: "PW Skills", url: "https://www.pwskills.com/course/cloud-computing", description: "AWS services, EC2, S3, Lambda, and cloud architecture fundamentals.", skills: ["aws","cloud","ec2","s3","lambda","devops","linux"], category: "Cloud", duration: "4 months", difficulty: "Beginner", rating: 4.1, price: { amount: 3499, currency: "INR", isFree: false }, certificationProvided: true },
  { title: "React - The Complete Guide", provider: "Udemy", url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/", description: "Dive in and learn React.js from scratch with hooks, Redux, React Router, Next.js and more.", skills: ["react","javascript","redux","react router","hooks","next.js"], category: "Web Development", duration: "48 hours", difficulty: "Intermediate", rating: 4.7, price: { amount: 3999, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "Node.js - The Complete Guide", provider: "Udemy", url: "https://www.udemy.com/course/nodejs-the-complete-guide/", description: "Build scalable server-side apps with Node.js, Express, MongoDB, and GraphQL.", skills: ["node.js","express","mongodb","graphql","rest api","javascript"], category: "Web Development", duration: "40 hours", difficulty: "Intermediate", rating: 4.6, price: { amount: 3999, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "Docker & Kubernetes: The Practical Guide", provider: "Udemy", url: "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/", description: "Master Docker and Kubernetes from basics to advanced orchestration.", skills: ["docker","kubernetes","containerization","devops","linux","yaml"], category: "DevOps", duration: "24 hours", difficulty: "Intermediate", rating: 4.7, price: { amount: 3999, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "Python for Everybody Specialization", provider: "Coursera", url: "https://www.coursera.org/specializations/python", description: "Learn to program and analyze data with Python. University of Michigan.", skills: ["python","data analysis","sql","json","web scraping"], category: "Data Science", duration: "8 months", difficulty: "Beginner", rating: 4.8, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "IBM Data Science Professional Certificate", provider: "Coursera", url: "https://www.coursera.org/professional-certificates/ibm-data-science", description: "Build data science skills with Python, SQL, machine learning, and data visualization.", skills: ["python","sql","machine learning","data visualization","pandas","jupyter"], category: "Data Science", duration: "5 months", difficulty: "Beginner", rating: 4.6, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Google IT Support Professional Certificate", provider: "Coursera", url: "https://www.coursera.org/professional-certificates/google-it-support", description: "Learn job-ready skills for IT support roles including networking and system administration.", skills: ["linux","networking","windows","troubleshooting","active directory","security"], category: "Cloud", duration: "6 months", difficulty: "Beginner", rating: 4.8, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Responsive Web Design", provider: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/responsive-web-design/", description: "Build 5 responsive websites using HTML, CSS, and modern design principles.", skills: ["html","css","responsive design","flexbox","grid","accessibility"], category: "Web Development", duration: "300 hours", difficulty: "Beginner", rating: 4.7, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "JavaScript Algorithms and Data Structures", provider: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/", description: "Learn JavaScript fundamentals, ES6+, regex, debugging, and data structures.", skills: ["javascript","es6","algorithms","data structures","debugging","regex"], category: "Computer Science", duration: "300 hours", difficulty: "Intermediate", rating: 4.6, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Frontend Developer (React) Certification", provider: "HackerRank", url: "https://www.hackerrank.com/skills-verification/frontend-developer-react", description: "Validate your React and frontend development skills with HackerRank.", skills: ["react","javascript","html","css","dom manipulation","hooks"], category: "Web Development", duration: "2 hours", difficulty: "Intermediate", rating: 4.3, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Backend Developer (Node.js) Certification", provider: "HackerRank", url: "https://www.hackerrank.com/skills-verification/backend-developer-node", description: "Prove your Node.js and backend development proficiency.", skills: ["node.js","express","rest api","mongodb","javascript","authentication"], category: "Web Development", duration: "2 hours", difficulty: "Intermediate", rating: 4.2, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "TypeScript for Professionals", provider: "Udemy", url: "https://www.udemy.com/course/typescript-for-professionals/", description: "Master TypeScript from basics to advanced types, generics, and decorators.", skills: ["typescript","javascript","generics","decorators","types"], category: "Web Development", duration: "12 hours", difficulty: "Intermediate", rating: 4.5, price: { amount: 1999, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "Git & GitHub Masterclass", provider: "Udemy", url: "https://www.udemy.com/course/git-and-github-masterclass/", description: "Learn Git version control and GitHub collaboration from scratch.", skills: ["git","github","version control","branching","ci/cd"], category: "DevOps", duration: "10 hours", difficulty: "Beginner", rating: 4.6, price: { amount: 1999, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "AWS Cloud Practitioner Essentials", provider: "Coursera", url: "https://www.coursera.org/learn/aws-cloud-practitioner-essentials", description: "Learn AWS cloud fundamentals, services, security, and pricing.", skills: ["aws","cloud","ec2","s3","iam","lambda"], category: "Cloud", duration: "6 weeks", difficulty: "Beginner", rating: 4.7, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: false },
  { title: "Meta Front-End Developer Professional Certificate", provider: "Coursera", url: "https://www.coursera.org/professional-certificates/meta-front-end-developer", description: "Build modern web apps with React from Meta. Industry-recognized certificate.", skills: ["react","javascript","html","css","react native","testing"], category: "Web Development", duration: "7 months", difficulty: "Beginner", rating: 4.7, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Machine Learning Specialization", provider: "Coursera", url: "https://www.coursera.org/specializations/machine-learning-introduction", description: "Andrew Stanford ML course. Supervised/unsupervised learning, neural networks.", skills: ["machine learning","python","tensorflow","neural networks","regression","classification"], category: "AI/ML", duration: "3 months", difficulty: "Intermediate", rating: 4.9, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Google UX Design Professional Certificate", provider: "Coursera", url: "https://www.coursera.org/professional-certificates/google-ux-design", description: "Learn UX research, wireframing, prototyping with Figma from Google.", skills: ["ux design","figma","wireframing","prototyping","user research","design thinking"], category: "Design", duration: "6 months", difficulty: "Beginner", rating: 4.8, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "SQL for Data Science", provider: "Coursera", url: "https://www.coursera.org/learn/sql-for-data-science", description: "Master SQL queries, joins, subqueries, and database design for data analysis.", skills: ["sql","database","queries","joins","subqueries","data analysis"], category: "Data Science", duration: "4 weeks", difficulty: "Beginner", rating: 4.5, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: false },
  { title: "Tailwind CSS from Scratch", provider: "Udemy", url: "https://www.udemy.com/course/twind/", description: "Build modern responsive UIs with Tailwind CSS utility-first framework.", skills: ["css","tailwind","responsive design","utility-first","html"], category: "Web Development", duration: "8 hours", difficulty: "Beginner", rating: 4.5, price: { amount: 1499, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "MongoDB University", provider: "freeCodeCamp", url: "https://university.mongodb.com/", description: "Official MongoDB courses covering CRUD, aggregation, indexing, and Atlas.", skills: ["mongodb","nosql","aggregation","indexing","atlas"], category: "Data Science", duration: "20 hours", difficulty: "Beginner", rating: 4.5, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "Next.js & React - The Complete Guide", provider: "Udemy", url: "https://www.udemy.com/course/nextjs-react-the-complete-guide/", description: "Build full-stack React apps with Next.js, SSR, SSG, API routes, and databases.", skills: ["next.js","react","ssr","typescript","prisma","tailwind"], category: "Web Development", duration: "22 hours", difficulty: "Intermediate", rating: 4.6, price: { amount: 3999, currency: "INR", isFree: false }, certificationProvided: false },
  { title: "Deep Learning Specialization", provider: "Coursera", url: "https://www.coursera.org/specializations/deep-learning", description: "Andrew Ng deep learning course. Neural networks, CNNs, RNNs, sequence models.", skills: ["deep learning","neural networks","tensorflow","cnn","rnn","python"], category: "AI/ML", duration: "5 months", difficulty: "Advanced", rating: 4.9, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: true },
  { title: "AWS Certified Solutions Architect", provider: "LinkedIn Learning", url: "https://www.linkedin.com/learning/aws-certified-solutions-architect-associate", description: "Prepare for the AWS SAA-C03 exam with hands-on labs and practice tests.", skills: ["aws","cloud","vpc","ec2","s3","iam","route53"], category: "Cloud", duration: "18 hours", difficulty: "Intermediate", rating: 4.6, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: false },
  { title: "DevOps with Docker, Kubernetes & Terraform", provider: "LinkedIn Learning", url: "https://www.linkedin.com/learning/devops-for-developers", description: "Container orchestration, IaC, and CI/CD pipelines for modern DevOps.", skills: ["docker","kubernetes","terraform","ci/cd","github actions","linux"], category: "DevOps", duration: "15 hours", difficulty: "Intermediate", rating: 4.5, price: { amount: 0, currency: "USD", isFree: true }, certificationProvided: false },
  { title: "Figma UI UX Design Essentials", provider: "Udemy", url: "https://www.udemy.com/course/figma-ux-ui-design-essentials/", description: "Learn Figma from scratch: auto layout, components, prototyping, and design systems.", skills: ["figma","ui design","ux design","prototyping","design systems"], category: "Design", duration: "11 hours", difficulty: "Beginner", rating: 4.6, price: { amount: 1999, currency: "INR", isFree: false }, certificationProvided: false },
];

const certifications = [
  { name: "AWS Cloud Practitioner", provider: "Amazon Web Services", abbrev: "AWS CP", category: "Cloud", skills: ["aws","cloud","iam","ec2","s3","lambda"], difficulty: "Beginner", examFee: { amount: 100, currency: "USD" }, validityMonths: 36, description: "Foundational understanding of AWS Cloud services, security, and pricing.", recommendedFor: ["Cloud Engineer","DevOps Engineer","Solutions Architect"], studyResources: [{ title: "AWS Cloud Practitioner Essentials", url: "https://www.coursera.org/learn/aws-cloud-practitioner-essentials", type: "course" }] },
  { name: "AWS Solutions Architect Associate", provider: "Amazon Web Services", abbrev: "AWS SAA", category: "Cloud", skills: ["aws","vpc","ec2","s3","route53","cloudfront","dynamodb"], difficulty: "Intermediate", examFee: { amount: 150, currency: "USD" }, validityMonths: 36, description: "Design distributed systems on AWS. VPC, load balancing, auto-scaling.", recommendedFor: ["Cloud Architect","Solutions Architect","DevOps Engineer"], studyResources: [{ title: "AWS SAA-C03 Prep", url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/", type: "course" }] },
  { name: "Google Cloud Associate Cloud Engineer", provider: "Google Cloud", abbrev: "GCP ACE", category: "Cloud", skills: ["gcp","gke","cloud sql","compute engine","cloud storage","kubernetes"], difficulty: "Beginner", examFee: { amount: 125, currency: "USD" }, validityMonths: 24, description: "Deploy, monitor, and manage solutions on Google Cloud Platform.", recommendedFor: ["Cloud Engineer","DevOps Engineer","Platform Engineer"], studyResources: [{ title: "GCP ACE Training", url: "https://www.coursera.org/professional-certificates/google-cloud-associate-cloud-engineer", type: "course" }] },
  { name: "Microsoft Azure Fundamentals", provider: "Microsoft", abbrev: "AZ-900", category: "Cloud", skills: ["azure","cloud","virtual machines","storage","networking"], difficulty: "Beginner", examFee: { amount: 99, currency: "USD" }, validityMonths: 24, description: "Foundational knowledge of cloud services and Microsoft Azure.", recommendedFor: ["Cloud Engineer","IT Administrator","Developer"], studyResources: [{ title: "AZ-900 Learning Path", url: "https://learn.microsoft.com/en-us/training/paths/az-900-describe-cloud-concepts/", type: "doc" }] },
  { name: "Microsoft Azure Developer Associate", provider: "Microsoft", abbrev: "AZ-204", category: "Cloud", skills: ["azure",".net","cosmos db","azure functions","app service","c#"], difficulty: "Intermediate", examFee: { amount: 165, currency: "USD" }, validityMonths: 24, description: "Design, build, test, and maintain cloud applications on Azure.", recommendedFor: ["Cloud Developer","Full Stack Developer","Backend Developer"], studyResources: [{ title: "AZ-204 Prep", url: "https://learn.microsoft.com/en-us/training/paths/az-204-describe-azure-app-services/", type: "doc" }] },
  { name: "HashiCorp Terraform Associate", provider: "HashiCorp", abbrev: "HCTA", category: "DevOps", skills: ["terraform","iac","infrastructure","cloud","provisioning"], difficulty: "Intermediate", examFee: { amount: 70, currency: "USD" }, validityMonths: 24, description: "Infrastructure as Code with Terraform for multi-cloud provisioning.", recommendedFor: ["DevOps Engineer","Cloud Engineer","SRE"], studyResources: [{ title: "Terraform Tutorials", url: "https://developer.hashicorp.com/terraform/tutorials", type: "doc" }] },
  { name: "Kubernetes Administrator (CKA)", provider: "Cloud Native Computing Foundation", abbrev: "CKA", category: "DevOps", skills: ["kubernetes","container orchestration","networking","security","storage","linux"], difficulty: "Advanced", examFee: { amount: 395, currency: "USD" }, validityMonths: 36, description: "Demonstrate competency in Kubernetes administration, scheduling, and networking.", recommendedFor: ["DevOps Engineer","Platform Engineer","SRE"], studyResources: [{ title: "CKA Exam Curriculum", url: "https://github.com/cncf/curriculum", type: "doc" }] },
  { name: "Meta Front-End Developer Professional Certificate", provider: "Meta", abbrev: "Meta FE", category: "Web Development", skills: ["react","javascript","html","css","react native","testing"], difficulty: "Beginner", examFee: { amount: 0, currency: "USD" }, validityMonths: 0, description: "Industry-recognized front-end development certificate from Meta.", recommendedFor: ["Frontend Developer","React Developer","Web Developer"], studyResources: [{ title: "Meta FE Course", url: "https://www.coursera.org/professional-certificates/meta-front-end-developer", type: "course" }] },
  { name: "CompTIA Security+", provider: "CompTIA", abbrev: "SY0-701", category: "Security", skills: ["security","network security","cryptography","access control","risk management"], difficulty: "Intermediate", examFee: { amount: 404, currency: "USD" }, validityMonths: 36, description: "Baseline cybersecurity skills for IT professionals.", recommendedFor: ["Security Analyst","Network Engineer","IT Administrator"], studyResources: [{ title: "CompTIA Security+ Study Guide", url: "https://www.comptia.org/certifications/security", type: "doc" }] },
  { name: "Google Associate Android Developer", provider: "Google", abbrev: "Google AD", category: "Mobile", skills: ["android","java","kotlin","android studio","mobile development"], difficulty: "Intermediate", examFee: { amount: 0, currency: "USD" }, validityMonths: 24, description: "Demonstrate proficiency in Android app development fundamentals.", recommendedFor: ["Android Developer","Mobile Developer"], studyResources: [{ title: "Android Developer Training", url: "https://developer.android.com/courses", type: "course" }] },
  { name: "MongoDB Certified Developer Associate", provider: "MongoDB", abbrev: "MongoDB Dev", category: "Data Science", skills: ["mongodb","nosql","aggregation","indexing","schema design"], difficulty: "Beginner", examFee: { amount: 150, currency: "USD" }, validityMonths: 24, description: "Validate skills in MongoDB CRUD operations, data modeling, and indexing.", recommendedFor: ["Backend Developer","Database Administrator","Full Stack Developer"], studyResources: [{ title: "MongoDB University", url: "https://university.mongodb.com/", type: "course" }] },
  { name: "Google Data Analytics Professional Certificate", provider: "Google", abbrev: "Google DA", category: "Data Science", skills: ["data analysis","sql","r programming","tableau","data visualization","spreadsheets"], difficulty: "Beginner", examFee: { amount: 0, currency: "USD" }, validityMonths: 0, description: "Learn data analytics skills for entry-level roles from Google.", recommendedFor: ["Data Analyst","Business Analyst"], studyResources: [{ title: "Google DA Course", url: "https://www.coursera.org/professional-certificates/google-data-analytics", type: "course" }] },
  { name: "Certified Kubernetes Application Developer", provider: "Cloud Native Computing Foundation", abbrev: "CKAD", category: "DevOps", skills: ["kubernetes","docker","helm","yaml","containerization","linux"], difficulty: "Advanced", examFee: { amount: 395, currency: "USD" }, validityMonths: 36, description: "Design, build, configure, and expose cloud-native applications for Kubernetes.", recommendedFor: ["DevOps Engineer","Cloud Developer","Platform Engineer"], studyResources: [{ title: "CKAD Exercises", url: "https://github.com/dgkanatsios/CKAD-exercises", type: "practice" }] },
  { name: "Certified Ethical Hacker", provider: "EC-Council", abbrev: "CEH", category: "Security", skills: ["penetration testing","ethical hacking","network security","web application security"], difficulty: "Advanced", examFee: { amount: 550, currency: "USD" }, validityMonths: 36, description: "Validate skills in ethical hacking and penetration testing methodologies.", recommendedFor: ["Security Analyst","Penetration Tester","Security Engineer"], studyResources: [{ title: "CEH Study Materials", url: "https://www.eccouncil.org/certified-ethical-hacker/", type: "doc" }] },
  { name: "Red Hat Certified System Administrator", provider: "Red Hat", abbrev: "RHCSA", category: "DevOps", skills: ["linux","red hat","system administration","shell scripting","networking"], difficulty: "Intermediate", examFee: { amount: 425, currency: "USD" }, validityMonths: 36, description: "Prove your ability to manage Red Hat Enterprise Linux systems.", recommendedFor: ["System Administrator","Linux Administrator","DevOps Engineer"], studyResources: [{ title: "RHCSA Prep", url: "https://www.redhat.com/en/services/training/rhcsa-preparation-guide", type: "doc" }] },
  { name: "Cisco Certified Network Associate", provider: "Cisco", abbrev: "CCNA", category: "Cloud", skills: ["networking","routing","switching","firewalls","cisco","dns"], difficulty: "Intermediate", examFee: { amount: 330, currency: "USD" }, validityMonths: 36, description: "Validate your skills in network fundamentals, IP services, and security.", recommendedFor: ["Network Engineer","System Administrator","Cloud Engineer"], studyResources: [{ title: "CCNA Study Resources", url: "https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html", type: "doc" }] },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("Connected to MongoDB");
  await Course.deleteMany({});
  await Certification.deleteMany({});
  await Course.insertMany(courses);
  await Certification.insertMany(certifications);
  console.log("Seeded", courses.length, "courses and", certifications.length, "certifications");
  process.exit(0);
}
seed().catch(e => { console.error(e); process.exit(1); });
